# Generated by Django 5.2.5 on 2025-10-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_description_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
