# Generated by Django 5.2.5 on 2025-10-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
