# Generated by Django 5.2.5 on 2025-10-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Ready To Shift', 'Ready To Shift'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Not Paid', max_length=30),
        ),
    ]
